### ISSUE TITLE
Accessing store from outside of vdux 

### ISSUE THREAD

**Issue by axdg** [vdux/vdux#14]
Hi @ashaffer, I've just taken read through the docs (haven't looked the source yet). There doesn't appear to be any mechanism for dispatching to the store from outside DOM event handlers created with vdux. 

How would one go about dispatching to the internal redux store in response to a `resize` or `popstate` event?

**Comment by ashaffer** [comment]
For `popstate` in particular I use [redux-effects-location](https://github.com/redux-effects/redux-effects-location). And in general the way to deal with things like that in vdux is to put them in your middleware and initiate them with an action. Then your middleware can dispatch new actions whenever the value changes.

Does that make sense?

**Comment by axdg** [comment]
Sure, It's a departure from how I'd normally deal with this when using redux/react - where resize, popstate or websocket event handlers dispatch actions themselves.

I guess I'll have to wire up some redux-effects-location style middleware for the others.

**Comment by axdg** [comment]
Or maybe just use virtex directly.

**Comment by ashaffer** [comment]
Ya, you're certainly free to use virtex directly. I think though the advantage of using middleware to contain all your side effects is that it's easy to ensure your app is universal, and also easy to see where everything originates. The middleware can really be very simple:

``` javascript
function resize ({dispatch}) {
  return next => action =>  action.type === INIT_RESIZE
    ? window.addEventListener('resize', resizeListener(dispatch))
    : next(action)
}

function resizeListener (dispatch) {
  return e => dispatch({type: RESIZE, width: window.innerWidth, height: window.innerHeight})
}
```

This ensures that you completely decouple the concerns of interpretation with the data itself.

**Comment by ashaffer** [comment]
So, you now have an official way to do this using [redux-thunk](https://github.com/gaearon/redux-thunk). I still strongly recommend against it, but for reusable components that need to do side-effectful things it's probably acceptable.

Specifically you may now return thunks from your lifecycle hooks / event handlers:

``` javascript
function onCreate () {
  return function (dispatch) {
    setTimeout(function () { dispatch(someAction) }, 300)
  }
}
```
