### ISSUE TITLE
Migrate from redux to koax?

### ISSUE THREAD

**Issue by ashaffer** [vdux/vdux#15]
I'm contemplating swapping out redux for [koax](https://github.com/koaxjs/koax) and [store](https://github.com/micro-js/store). Koax essentially implements redux style middleware, but with generators, which is IMO a much more natural pattern for that type of middleware. This has the downside of forcing you to include the generator runtime in your projects (though it's pretty small, as long as you don't include all of core-js).

It's benefits though are a consistent, clean syntax around effects and more long-lived transactional patterns. E.g.

``` javascript
import {delay} from '@koax/timing'

function *onCreate ({local}) {
  yield delay(1000)
  yield local(openMenu)
}
```

This issue of how to deal with timing is, I think, the only significant issue remaining that hinders a high degree of reusability between components.

I should also note that this can be accomplished using redux and [redux-gen](https://github.com/weo-edu/redux-gen) or [redux-effects](https://github.com/redux-effects/redux-effects), but I think koax solves it in the most natural and clean way.

Thoughts? Objections?

@axdg @queckezz @ahdinosaur I know you guys have been using it a bit.

PS: I made a few other changes to the most recent version of vdux. I added special `Window/Body/Document` components that allow you to listen for events on any of the respective elements, so that you don't have to do awkward binding/unbinding of those handlers. [More info](https://github.com/vdux/vdux#global-event-handlers).

I also removed refs, in favor of the pattern now [described in the readme](https://github.com/vdux/vdux#refs).

**Comment by axdg** [comment]
So here are my thoughts...

First, regarding `window/document/body` - this is awesome. It will help a great deal with, for instance; `popstate`, `resize` and `hashchange` events - the router example in the docs is great. 

vdux is pretty opinionated about dispatching data from these sorts of events into the store i.e. middleware (or these new global components) should be used to listen for events that are not coming directly from the UI, this is high level, and pretty different to what I'm used to, but it's growing on me. There should probably be an example in the docs for dealing with events that aren't attached to the DOM in any way (for instance, a websocket push or a message send/receive to/from a webworker).

Regarding [koax](https://github.com/koaxjs/koax), I personally really like [co](https://github.com/tj/co) and all of the similar patterns for implementing coroutines in JS. The big value of these for me is the composability and how easy it makes async code to follow (@koax/timing for instance makes a `setTimeout` appear to be a blocking `sleep`). I would be perfectly content with using koax and @f/store. There will be a perf impact though (just as there is in koa relative to express), but this will probably be negligible.

**Comment by queckezz** [comment]
`koax` looks promising! Haven't dug into this to much but as far as I understand, this would mean we would standardize flow control into vdux? I'm also assuming this is meant to replace both component level and application level flow, right? Right now there are so many options (sagas, effects in middleware, redux-thunk, [effects in reducers](https://github.com/raisemarketplace/redux-loop) etc.) of what flow control library to use, so I'm unsure if it's the right move to settle down to one specific style atm. On the other side, vdux is meant to be an opinionated stack. You are always free to build up your own stack with `virtex`.

I'm also not really sure if it's beneficial to have such a powerful control flow library on simple lifecycle handlers. Mostly you delegate the work to an outside application-level saga. (Might be totally wrong on this one).

If you're deciding to make the switch we should ensure to have some kind of compatibility layer between redux middleware and `koax`. I've seen `koax-logger` which is just a wrapper around `redux-logger`. I think it would be a bad move to reinvent all those modules again or wrap them. We should come up something similar to [koa-convert](https://github.com/koajs/convert) or make koax compatible with redux-style middleware.

> PS: I made a few other changes to the most recent version of vdux. I added special Window/Body/Document components that allow you to listen for events on any of the respective elements, so that you don't have to do awkward binding/unbinding of those handlers. More info.

Once again - awesome work! Really simplifies a lot. Also, thanks for inviting me to the org. Really excited to contribute back!

**Comment by ashaffer** [comment]
Hmm ya re-implementing the middleware would be annoying. It's also possible to accomplish the same goals using redux-gen or redux-effects. And I totally agree that it really sucks to have to be opinionated about effects and effect composition.

I suppose I should have more clearly articulated the problem that led me to this, and see if we can figure out a solution that doesn't force us to be opinionated about effects. This is what led me to add the window/document/body components, so that you didn't have to have an opinion about effects in order to listen on those elements. But then I got stuck trying to do the same for timing.

A concrete example. Let's say you make a `Hover` component:

``` javascript
function render ({state, children, local}) {
  return (
    <span onMouseOver={local(hover)} onMouseOut={local(unhover)}>
      {
        children.map(child => isFunction(child) ? child(state.hovering) : child)
      }
    </span>
  )
}
```

Which you might use like this:

`<Hover><SomeThing />{hover => hover && <Tooltip message='tooltip for SomeThing' />}</Hover>`

Now let's say you want to only show that tooltip if you've hovered over SomeThing for 500ms. How do you accomplish this without being opinionated about middleware in the stack (rendering your heretofore reusable component unreusable)?

I think that timing is the only remaining thing that is sufficiently common in reusable components that it requires a solution in vdux. Once we have that, we can start creating a nice ecosystem of reusable widgets.

But how should it work? I can think of a few possibilities:
- Be opinionated about effects generally
- Give components/hooks direct access to `dispatch`. This would let you say, dispatch after a setTimeout. I tend to dislike this approach because it hides state and reduces debuggability and inspectability.
- Create some sort of special component/mechanism to deal specifically with timing, analogous to the window/document/body components. E.g. `Timer/Raf/Interval` components, perhaps?

But those are just the things that I can think of! And none of them seem totally ideal, although as i'm writing this I now lean maybe most towards option 3. But i'd love to hear additional ideas if you guys have some. 

The biggest downside of number 3 is that if this pattern continues, vdux just becomes a collection of hacks to deal with these types of cases, which is not super desirable. But if it's true that timing is really the only thing like this, then maybe it makes sense to deal with it as narrowly as possible.

**Comment by ashaffer** [comment]
I'm going to sketch an idea, let me know what you guys think. Consider a `<Delay/>` component, used like this:

``` javascript
function render () {
  return (
    <Delay time='300'>
      <Tooltip />
    </Delay>
  )
}
```

Where `<Tooltip />` is rendered after 300ms. The semantics would be that `onCreate` the timer begins. If the `time` prop is altered before the timer has fired, the original timeout is cancelled and replaced with a new one, with time equal to `time - elapsedFromCreate`. `onRemove`, if the timer has not fired yet, it is cancelled.  I think this renders simple one of the more awkward patterns around timers (cancelling the timer if some condition occurs before it fires).  Consider the more full delayed tooltip example:

``` javascript
function render () {
  return (
    <Hover>
      <HoverableEntity />
      {hover => hover && <Delay time='300'><Tooltip /></Delay>}
    </Hover>
  )
}
```

All of the cancellation is built in. If `hover` becomes false before the timer fires, nothing happens - and the cleanup of the timer is managed naturally by the component lifecycle. Everything is testable because it's declaratively specified in the DOM tree, so it's more acceptable for the `Delay` component to be doing something like imperative dispatching under the hood.

**Comment by ashaffer** [comment]
Hmm...ok I think the minimal, least opinionated thing I can do is to include [redux-thunk](https://github.com/gaearon/redux-thunk) by default, and then create the timing components described above using thunks.

Doing this doesn't force you to use redux-thunk if you don't want to or to enable generators or anything like that, and it's also extremely small, so the cost is negligible. Thunks are not my preferred style of effect management, but I think it is probably a necessary primitive to provide, and just recommend that people use the timing components.

**Comment by queckezz** [comment]
Cool yea that sounds reasonable to me and is the best compromise. One thing we could do, is to have a `redux-thunk` which only exposes `dispatch()` and not `getState()`. I think this would mostly prevent people from doing hacky things and only use it for timing related things. But that might introduce other problems.

**Comment by ashaffer** [comment]
@queckezz That's probably a good idea. I think i'm going to leave that alone for now and just go with the standard redux-thunk, but if it gets to be a problem i'll do that.

vdux has redux-thunk in it now, and i've made a [delay component](https://github.com/vdux-components/delay).

I'm gonna close this issue now since I think it's resolved, but let me know if you have questions/comments/criticisms about the way i'm doing timing there.
