### ISSUE TITLE
routing example

### ISSUE THREAD

**Issue by matthewmueller** [vdux/vdux#2]
hey man! 

loving how this library is coming together. just wondering if you've thought about routing at all.

would love to see a routing example if you have a chance.

**Comment by ashaffer** [comment]
I'm working on a local state example at the moment using [redux-ephemeral](https://github.com/ashaffer/redux-ephemeral).  Once I get that worked out i'll try to create an example around routing.

I had been developing an application in deku using some of these ideas, and the way my router worked there is that it was just a pure function that returned a component.  E.g.

```
export default Router({
  '/:username': (state, context) => <Profile user={context.username} />
  // ...etc
})
```

And then my main App component did something like this:

``` javascript
import router from './router'

function render (props) {
  const currentPage = router(props.url, props)
  return (
    <div>
      {currentPage}
    </div>
  )
}
```

This notably does not try to address things like data-fetching directly.  I think that can be handled externally, or inside of the `beforeMount` hooks for the components.

**Comment by matthewmueller** [comment]
Ah very cool, thanks for the example. And so would the params be in a redux store so they're accessible from child components?

**Comment by ashaffer** [comment]
The way I have it implemented in my other app, the only thing that lives in redux is the current url.  Everything else is computed from that.  So the router parses out the parameters and passes it as the second argument to the route handler, which can then use that to pass it down to children or whatever it wants.  It also passes in the remaining portion of the url, so the routers can compose.

EDIT: Actually if you want to see it it's up here: [deku-scrubs/router](https://github.com/deku-scrubs/router).  Pay no attention to what the docs say, it works the way I described above, I just haven't updated them yet.

**Comment by matthewmueller** [comment]
awesome, thanks man!
