### ISSUE TITLE
todo example: forgot to commit `middleware/persist.js` ?

### ISSUE THREAD

**Issue by queckezz** [vdux/vdux#5]
[examples/todo/store.js#11](https://github.com/ashaffer/vdux/blob/master/examples/todo/store.js#L11)

`middleware/` folder is not committed atm.

**Comment by ashaffer** [comment]
Ah, I totally did.  Now i'm away from the machine that has that file for a few days lol.  Fortunately it is short so i'll rewrite it and push it momentarily.

**Comment by ashaffer** [comment]
Ok added it back in.  Let me know if you have any issues with it - I just rewrote it and tested it quickly.

**Comment by queckezz** [comment]
Awesome! Looking great. Just tested it, and works fine now :)
