### ISSUE TITLE
example using vdux-client?

### ISSUE THREAD

**Issue by matthewmueller** [vdux/vdux#8]
hey there,

trying to figure out how to get the `basic` example working with `vdux-client`. 

more specifically, i'm not sure how to handle everything being wrapped in `app`, like what code needs to be aware of it and what code does not.

do you have an example or some docs i can take a look at on how to use it?

**Comment by ashaffer** [comment]
Just converted the todo example real quick and pushed it. `app` is just a function that accepts state and returns a virtual dom tree. So like, as simple as `state => <Main {...state} />`.

I plan on adding some more details soon.

EDIT: Ah, I realize you may be confused about vdux-client's role.  It's just a bundle of middleware. You still need to use vdux, vdux-client just makes it easier to initialize all the middleware in a sane way (analogous to babel6 presets). So, vdux-client just helps you create the redux store store that you pass to vdux.

**Comment by matthewmueller** [comment]
just noticed you updated the docs. sorry for all the confusion, quite a bit to digest. thanks!
